### PR TITLE
Update to java 17

### PR DESCRIPTION
**Pull request by dineshudayakumar**

### CODE REVIEW

**Review by asafonov303 — APPROVED** [review]

**Comment by eriksw** [comment]
The renovate config should be updated too. There is a restriction that only exists because of old Java.

**Comment by dineshudayakumar** [comment]
> 

I have updated the renovate.json

**Review by asafonov303 — APPROVED** [review]

**Comment by eriksw** [comment]
Thank you. Have the other pending updates that were failing due to Java upgrade been incorporated into this PR? If not, we should do that before we cut 2.0.0, but this seems like it's probably okay for an initial merge.

**Comment by dineshudayakumar** [comment]
> Thank you. Have the other pending updates that were failing due to Java upgrade been incorporated into this PR? If not, we should do that before we cut 2.0.0, but this seems like it's probably okay for an initial merge.

No more changes anticipated in this repo for the java upgrade. (only in storenet it will be 2 phase, 1st upgrade to java 17 and later fop lib will be updated to 2.8)

**Pull request merged**
